### PR TITLE
20 clean up the readme

### LINKED ISSUE #20: Clean up the `ReadMe`
Please move our topic draft out of the readme into the Wiki and write a short objective

### PR DESCRIPTION
**Pull request by ganz-anders**
please review and merge

### CODE REVIEW

**Comment by BjaJac** [comment]
Please rename the Wiki-page in "Entwurf" or "Grob-Entwurf" since it is way too specific to be our "Thema".
Please remember to change that in the READme too.

**Comment by BjaJac** [comment]
Also i would like to see some more information concerning the functionality of the system (not the implementation/realization in the background)
Could you do this?

**Comment by ganz-anders** [comment]
I changed it again, what do you say?

**Comment by BjaJac** [comment]
Still not not exactly what i meant. I will contact you directly for further information.

**Comment by ganz-anders** [comment]
I updated it, please look in the issue for review instructions

**Pull request merged**
